#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TrabajoYpf")]
	public partial class DCDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserteTipoProducto(eTipoProducto instance);
    partial void UpdateeTipoProducto(eTipoProducto instance);
    partial void DeleteeTipoProducto(eTipoProducto instance);
    partial void InserteTipoPago(eTipoPago instance);
    partial void UpdateeTipoPago(eTipoPago instance);
    partial void DeleteeTipoPago(eTipoPago instance);
    partial void InserteTipoCombustible(eTipoCombustible instance);
    partial void UpdateeTipoCombustible(eTipoCombustible instance);
    partial void DeleteeTipoCombustible(eTipoCombustible instance);
    partial void InserteTarjeta(eTarjeta instance);
    partial void UpdateeTarjeta(eTarjeta instance);
    partial void DeleteeTarjeta(eTarjeta instance);
    partial void InserteSocio(eSocio instance);
    partial void UpdateeSocio(eSocio instance);
    partial void DeleteeSocio(eSocio instance);
    partial void InserteProducto(eProducto instance);
    partial void UpdateeProducto(eProducto instance);
    partial void DeleteeProducto(eProducto instance);
    partial void InserteMarca(eMarca instance);
    partial void UpdateeMarca(eMarca instance);
    partial void DeleteeMarca(eMarca instance);
    partial void InserteLugarRetiro(eLugarRetiro instance);
    partial void UpdateeLugarRetiro(eLugarRetiro instance);
    partial void DeleteeLugarRetiro(eLugarRetiro instance);
    partial void InserteLocalidad(eLocalidad instance);
    partial void UpdateeLocalidad(eLocalidad instance);
    partial void DeleteeLocalidad(eLocalidad instance);
    partial void InserteEmpleado(eEmpleado instance);
    partial void UpdateeEmpleado(eEmpleado instance);
    partial void DeleteeEmpleado(eEmpleado instance);
    partial void InserteCombustible(eCombustible instance);
    partial void UpdateeCombustible(eCombustible instance);
    partial void DeleteeCombustible(eCombustible instance);
    partial void InserteCiudad(eCiudad instance);
    partial void UpdateeCiudad(eCiudad instance);
    partial void DeleteeCiudad(eCiudad instance);
    partial void InserteCargaCombustibleSocio(eCargaCombustibleSocio instance);
    partial void UpdateeCargaCombustibleSocio(eCargaCombustibleSocio instance);
    partial void DeleteeCargaCombustibleSocio(eCargaCombustibleSocio instance);
    partial void InserteCargaCombustible(eCargaCombustible instance);
    partial void UpdateeCargaCombustible(eCargaCombustible instance);
    partial void DeleteeCargaCombustible(eCargaCombustible instance);
    partial void InserteCanje(eCanje instance);
    partial void UpdateeCanje(eCanje instance);
    partial void DeleteeCanje(eCanje instance);
    #endregion
		
		public DCDataContext() : 
				base(global::CapaDatos.Properties.Settings.Default.TrabajoYpfConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<eTipoProducto> eTipoProductos
		{
			get
			{
				return this.GetTable<eTipoProducto>();
			}
		}
		
		public System.Data.Linq.Table<eTipoPago> eTipoPagos
		{
			get
			{
				return this.GetTable<eTipoPago>();
			}
		}
		
		public System.Data.Linq.Table<eTipoCombustible> eTipoCombustibles
		{
			get
			{
				return this.GetTable<eTipoCombustible>();
			}
		}
		
		public System.Data.Linq.Table<eTarjeta> eTarjetas
		{
			get
			{
				return this.GetTable<eTarjeta>();
			}
		}
		
		public System.Data.Linq.Table<eSocio> eSocios
		{
			get
			{
				return this.GetTable<eSocio>();
			}
		}
		
		public System.Data.Linq.Table<eProducto> eProductos
		{
			get
			{
				return this.GetTable<eProducto>();
			}
		}
		
		public System.Data.Linq.Table<eMarca> eMarcas
		{
			get
			{
				return this.GetTable<eMarca>();
			}
		}
		
		public System.Data.Linq.Table<eLugarRetiro> eLugarRetiros
		{
			get
			{
				return this.GetTable<eLugarRetiro>();
			}
		}
		
		public System.Data.Linq.Table<eLocalidad> eLocalidads
		{
			get
			{
				return this.GetTable<eLocalidad>();
			}
		}
		
		public System.Data.Linq.Table<eEmpleado> eEmpleados
		{
			get
			{
				return this.GetTable<eEmpleado>();
			}
		}
		
		public System.Data.Linq.Table<eCombustible> eCombustibles
		{
			get
			{
				return this.GetTable<eCombustible>();
			}
		}
		
		public System.Data.Linq.Table<eCiudad> eCiudads
		{
			get
			{
				return this.GetTable<eCiudad>();
			}
		}
		
		public System.Data.Linq.Table<eCargaCombustibleSocio> eCargaCombustibleSocios
		{
			get
			{
				return this.GetTable<eCargaCombustibleSocio>();
			}
		}
		
		public System.Data.Linq.Table<eCargaCombustible> eCargaCombustibles
		{
			get
			{
				return this.GetTable<eCargaCombustible>();
			}
		}
		
		public System.Data.Linq.Table<eCanje> eCanjes
		{
			get
			{
				return this.GetTable<eCanje>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoProducto")]
	public partial class eTipoProducto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre;
		
		private string _descripcion;
		
		private EntitySet<eProducto> _eProductos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public eTipoProducto()
		{
			this._eProductos = new EntitySet<eProducto>(new Action<eProducto>(this.attach_eProductos), new Action<eProducto>(this.detach_eProductos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(255)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoProducto_Producto", Storage="_eProductos", ThisKey="id", OtherKey="fkTipo")]
		public EntitySet<eProducto> eProductos
		{
			get
			{
				return this._eProductos;
			}
			set
			{
				this._eProductos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_eProductos(eProducto entity)
		{
			this.SendPropertyChanging();
			entity.eTipoProducto = this;
		}
		
		private void detach_eProductos(eProducto entity)
		{
			this.SendPropertyChanging();
			entity.eTipoProducto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoPago")]
	public partial class eTipoPago : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre;
		
		private string _descripcion;
		
		private EntitySet<eCargaCombustibleSocio> _eCargaCombustibleSocios;
		
		private EntitySet<eCargaCombustible> _eCargaCombustibles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public eTipoPago()
		{
			this._eCargaCombustibleSocios = new EntitySet<eCargaCombustibleSocio>(new Action<eCargaCombustibleSocio>(this.attach_eCargaCombustibleSocios), new Action<eCargaCombustibleSocio>(this.detach_eCargaCombustibleSocios));
			this._eCargaCombustibles = new EntitySet<eCargaCombustible>(new Action<eCargaCombustible>(this.attach_eCargaCombustibles), new Action<eCargaCombustible>(this.detach_eCargaCombustibles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(255)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoPago_CargaCombustibleSocio", Storage="_eCargaCombustibleSocios", ThisKey="id", OtherKey="fkPago")]
		public EntitySet<eCargaCombustibleSocio> eCargaCombustibleSocios
		{
			get
			{
				return this._eCargaCombustibleSocios;
			}
			set
			{
				this._eCargaCombustibleSocios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoPago_CargaCombustible", Storage="_eCargaCombustibles", ThisKey="id", OtherKey="fkPago")]
		public EntitySet<eCargaCombustible> eCargaCombustibles
		{
			get
			{
				return this._eCargaCombustibles;
			}
			set
			{
				this._eCargaCombustibles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_eCargaCombustibleSocios(eCargaCombustibleSocio entity)
		{
			this.SendPropertyChanging();
			entity.eTipoPago = this;
		}
		
		private void detach_eCargaCombustibleSocios(eCargaCombustibleSocio entity)
		{
			this.SendPropertyChanging();
			entity.eTipoPago = null;
		}
		
		private void attach_eCargaCombustibles(eCargaCombustible entity)
		{
			this.SendPropertyChanging();
			entity.eTipoPago = this;
		}
		
		private void detach_eCargaCombustibles(eCargaCombustible entity)
		{
			this.SendPropertyChanging();
			entity.eTipoPago = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoCombustible")]
	public partial class eTipoCombustible : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nombre;
		
		private string _descripcion;
		
		private EntitySet<eCombustible> _eCombustibles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public eTipoCombustible()
		{
			this._eCombustibles = new EntitySet<eCombustible>(new Action<eCombustible>(this.attach_eCombustibles), new Action<eCombustible>(this.detach_eCombustibles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(255)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoCombustible_Combustible", Storage="_eCombustibles", ThisKey="nombre", OtherKey="fkTipo")]
		public EntitySet<eCombustible> eCombustibles
		{
			get
			{
				return this._eCombustibles;
			}
			set
			{
				this._eCombustibles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_eCombustibles(eCombustible entity)
		{
			this.SendPropertyChanging();
			entity.eTipoCombustible = this;
		}
		
		private void detach_eCombustibles(eCombustible entity)
		{
			this.SendPropertyChanging();
			entity.eTipoCombustible = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tarjeta")]
	public partial class eTarjeta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _numTarjeta;
		
		private System.Nullable<int> _puntos;
		
		private System.Nullable<System.DateTime> _fecVen;
		
		private EntitySet<eSocio> _eSocios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnumTarjetaChanging(int value);
    partial void OnnumTarjetaChanged();
    partial void OnpuntosChanging(System.Nullable<int> value);
    partial void OnpuntosChanged();
    partial void OnfecVenChanging(System.Nullable<System.DateTime> value);
    partial void OnfecVenChanged();
    #endregion
		
		public eTarjeta()
		{
			this._eSocios = new EntitySet<eSocio>(new Action<eSocio>(this.attach_eSocios), new Action<eSocio>(this.detach_eSocios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numTarjeta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int numTarjeta
		{
			get
			{
				return this._numTarjeta;
			}
			set
			{
				if ((this._numTarjeta != value))
				{
					this.OnnumTarjetaChanging(value);
					this.SendPropertyChanging();
					this._numTarjeta = value;
					this.SendPropertyChanged("numTarjeta");
					this.OnnumTarjetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puntos", DbType="Int")]
		public System.Nullable<int> puntos
		{
			get
			{
				return this._puntos;
			}
			set
			{
				if ((this._puntos != value))
				{
					this.OnpuntosChanging(value);
					this.SendPropertyChanging();
					this._puntos = value;
					this.SendPropertyChanged("puntos");
					this.OnpuntosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecVen", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecVen
		{
			get
			{
				return this._fecVen;
			}
			set
			{
				if ((this._fecVen != value))
				{
					this.OnfecVenChanging(value);
					this.SendPropertyChanging();
					this._fecVen = value;
					this.SendPropertyChanged("fecVen");
					this.OnfecVenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tarjeta_Socio", Storage="_eSocios", ThisKey="numTarjeta", OtherKey="fkTarjeta")]
		public EntitySet<eSocio> eSocios
		{
			get
			{
				return this._eSocios;
			}
			set
			{
				this._eSocios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_eSocios(eSocio entity)
		{
			this.SendPropertyChanging();
			entity.eTarjeta = this;
		}
		
		private void detach_eSocios(eSocio entity)
		{
			this.SendPropertyChanging();
			entity.eTarjeta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Socio")]
	public partial class eSocio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _numSocio;
		
		private string _apyn;
		
		private System.Nullable<System.DateTime> _fecnac;
		
		private int _dni;
		
		private System.Nullable<int> _fkLocalidad;
		
		private System.Nullable<int> _fkTarjeta;
		
		private EntitySet<eCargaCombustibleSocio> _eCargaCombustibleSocios;
		
		private EntitySet<eCanje> _eCanjes;
		
		private EntityRef<eTarjeta> _eTarjeta;
		
		private EntityRef<eLocalidad> _eLocalidad;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnumSocioChanging(int value);
    partial void OnnumSocioChanged();
    partial void OnapynChanging(string value);
    partial void OnapynChanged();
    partial void OnfecnacChanging(System.Nullable<System.DateTime> value);
    partial void OnfecnacChanged();
    partial void OndniChanging(int value);
    partial void OndniChanged();
    partial void OnfkLocalidadChanging(System.Nullable<int> value);
    partial void OnfkLocalidadChanged();
    partial void OnfkTarjetaChanging(System.Nullable<int> value);
    partial void OnfkTarjetaChanged();
    #endregion
		
		public eSocio()
		{
			this._eCargaCombustibleSocios = new EntitySet<eCargaCombustibleSocio>(new Action<eCargaCombustibleSocio>(this.attach_eCargaCombustibleSocios), new Action<eCargaCombustibleSocio>(this.detach_eCargaCombustibleSocios));
			this._eCanjes = new EntitySet<eCanje>(new Action<eCanje>(this.attach_eCanjes), new Action<eCanje>(this.detach_eCanjes));
			this._eTarjeta = default(EntityRef<eTarjeta>);
			this._eLocalidad = default(EntityRef<eLocalidad>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numSocio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int numSocio
		{
			get
			{
				return this._numSocio;
			}
			set
			{
				if ((this._numSocio != value))
				{
					this.OnnumSocioChanging(value);
					this.SendPropertyChanging();
					this._numSocio = value;
					this.SendPropertyChanged("numSocio");
					this.OnnumSocioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apyn", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string apyn
		{
			get
			{
				return this._apyn;
			}
			set
			{
				if ((this._apyn != value))
				{
					this.OnapynChanging(value);
					this.SendPropertyChanging();
					this._apyn = value;
					this.SendPropertyChanged("apyn");
					this.OnapynChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecnac", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecnac
		{
			get
			{
				return this._fecnac;
			}
			set
			{
				if ((this._fecnac != value))
				{
					this.OnfecnacChanging(value);
					this.SendPropertyChanging();
					this._fecnac = value;
					this.SendPropertyChanged("fecnac");
					this.OnfecnacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dni", DbType="Int NOT NULL")]
		public int dni
		{
			get
			{
				return this._dni;
			}
			set
			{
				if ((this._dni != value))
				{
					this.OndniChanging(value);
					this.SendPropertyChanging();
					this._dni = value;
					this.SendPropertyChanged("dni");
					this.OndniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkLocalidad", DbType="Int")]
		public System.Nullable<int> fkLocalidad
		{
			get
			{
				return this._fkLocalidad;
			}
			set
			{
				if ((this._fkLocalidad != value))
				{
					if (this._eLocalidad.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkLocalidadChanging(value);
					this.SendPropertyChanging();
					this._fkLocalidad = value;
					this.SendPropertyChanged("fkLocalidad");
					this.OnfkLocalidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkTarjeta", DbType="Int")]
		public System.Nullable<int> fkTarjeta
		{
			get
			{
				return this._fkTarjeta;
			}
			set
			{
				if ((this._fkTarjeta != value))
				{
					if (this._eTarjeta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkTarjetaChanging(value);
					this.SendPropertyChanging();
					this._fkTarjeta = value;
					this.SendPropertyChanged("fkTarjeta");
					this.OnfkTarjetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Socio_CargaCombustibleSocio", Storage="_eCargaCombustibleSocios", ThisKey="numSocio", OtherKey="fkSocio")]
		public EntitySet<eCargaCombustibleSocio> eCargaCombustibleSocios
		{
			get
			{
				return this._eCargaCombustibleSocios;
			}
			set
			{
				this._eCargaCombustibleSocios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Socio_Canje", Storage="_eCanjes", ThisKey="numSocio", OtherKey="fkSocio")]
		public EntitySet<eCanje> eCanjes
		{
			get
			{
				return this._eCanjes;
			}
			set
			{
				this._eCanjes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tarjeta_Socio", Storage="_eTarjeta", ThisKey="fkTarjeta", OtherKey="numTarjeta", IsForeignKey=true)]
		public eTarjeta eTarjeta
		{
			get
			{
				return this._eTarjeta.Entity;
			}
			set
			{
				eTarjeta previousValue = this._eTarjeta.Entity;
				if (((previousValue != value) 
							|| (this._eTarjeta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eTarjeta.Entity = null;
						previousValue.eSocios.Remove(this);
					}
					this._eTarjeta.Entity = value;
					if ((value != null))
					{
						value.eSocios.Add(this);
						this._fkTarjeta = value.numTarjeta;
					}
					else
					{
						this._fkTarjeta = default(Nullable<int>);
					}
					this.SendPropertyChanged("eTarjeta");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Localidad_Socio", Storage="_eLocalidad", ThisKey="fkLocalidad", OtherKey="id", IsForeignKey=true)]
		public eLocalidad eLocalidad
		{
			get
			{
				return this._eLocalidad.Entity;
			}
			set
			{
				eLocalidad previousValue = this._eLocalidad.Entity;
				if (((previousValue != value) 
							|| (this._eLocalidad.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eLocalidad.Entity = null;
						previousValue.eSocios.Remove(this);
					}
					this._eLocalidad.Entity = value;
					if ((value != null))
					{
						value.eSocios.Add(this);
						this._fkLocalidad = value.id;
					}
					else
					{
						this._fkLocalidad = default(Nullable<int>);
					}
					this.SendPropertyChanged("eLocalidad");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_eCargaCombustibleSocios(eCargaCombustibleSocio entity)
		{
			this.SendPropertyChanging();
			entity.eSocio = this;
		}
		
		private void detach_eCargaCombustibleSocios(eCargaCombustibleSocio entity)
		{
			this.SendPropertyChanging();
			entity.eSocio = null;
		}
		
		private void attach_eCanjes(eCanje entity)
		{
			this.SendPropertyChanging();
			entity.eSocio = this;
		}
		
		private void detach_eCanjes(eCanje entity)
		{
			this.SendPropertyChanging();
			entity.eSocio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Producto")]
	public partial class eProducto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre;
		
		private System.Nullable<int> _valor;
		
		private System.Nullable<int> _stock;
		
		private System.Nullable<int> _fkMarca;
		
		private System.Nullable<int> _fkTipo;
		
		private EntitySet<eCanje> _eCanjes;
		
		private EntityRef<eTipoProducto> _eTipoProducto;
		
		private EntityRef<eMarca> _eMarca;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnvalorChanging(System.Nullable<int> value);
    partial void OnvalorChanged();
    partial void OnstockChanging(System.Nullable<int> value);
    partial void OnstockChanged();
    partial void OnfkMarcaChanging(System.Nullable<int> value);
    partial void OnfkMarcaChanged();
    partial void OnfkTipoChanging(System.Nullable<int> value);
    partial void OnfkTipoChanged();
    #endregion
		
		public eProducto()
		{
			this._eCanjes = new EntitySet<eCanje>(new Action<eCanje>(this.attach_eCanjes), new Action<eCanje>(this.detach_eCanjes));
			this._eTipoProducto = default(EntityRef<eTipoProducto>);
			this._eMarca = default(EntityRef<eMarca>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="Int")]
		public System.Nullable<int> valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnvalorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("valor");
					this.OnvalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stock", DbType="Int")]
		public System.Nullable<int> stock
		{
			get
			{
				return this._stock;
			}
			set
			{
				if ((this._stock != value))
				{
					this.OnstockChanging(value);
					this.SendPropertyChanging();
					this._stock = value;
					this.SendPropertyChanged("stock");
					this.OnstockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkMarca", DbType="Int")]
		public System.Nullable<int> fkMarca
		{
			get
			{
				return this._fkMarca;
			}
			set
			{
				if ((this._fkMarca != value))
				{
					if (this._eMarca.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkMarcaChanging(value);
					this.SendPropertyChanging();
					this._fkMarca = value;
					this.SendPropertyChanged("fkMarca");
					this.OnfkMarcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkTipo", DbType="Int")]
		public System.Nullable<int> fkTipo
		{
			get
			{
				return this._fkTipo;
			}
			set
			{
				if ((this._fkTipo != value))
				{
					if (this._eTipoProducto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkTipoChanging(value);
					this.SendPropertyChanging();
					this._fkTipo = value;
					this.SendPropertyChanged("fkTipo");
					this.OnfkTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Canje", Storage="_eCanjes", ThisKey="id", OtherKey="fkProducto")]
		public EntitySet<eCanje> eCanjes
		{
			get
			{
				return this._eCanjes;
			}
			set
			{
				this._eCanjes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoProducto_Producto", Storage="_eTipoProducto", ThisKey="fkTipo", OtherKey="id", IsForeignKey=true)]
		public eTipoProducto eTipoProducto
		{
			get
			{
				return this._eTipoProducto.Entity;
			}
			set
			{
				eTipoProducto previousValue = this._eTipoProducto.Entity;
				if (((previousValue != value) 
							|| (this._eTipoProducto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eTipoProducto.Entity = null;
						previousValue.eProductos.Remove(this);
					}
					this._eTipoProducto.Entity = value;
					if ((value != null))
					{
						value.eProductos.Add(this);
						this._fkTipo = value.id;
					}
					else
					{
						this._fkTipo = default(Nullable<int>);
					}
					this.SendPropertyChanged("eTipoProducto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Marca_Producto", Storage="_eMarca", ThisKey="fkMarca", OtherKey="id", IsForeignKey=true)]
		public eMarca eMarca
		{
			get
			{
				return this._eMarca.Entity;
			}
			set
			{
				eMarca previousValue = this._eMarca.Entity;
				if (((previousValue != value) 
							|| (this._eMarca.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eMarca.Entity = null;
						previousValue.eProductos.Remove(this);
					}
					this._eMarca.Entity = value;
					if ((value != null))
					{
						value.eProductos.Add(this);
						this._fkMarca = value.id;
					}
					else
					{
						this._fkMarca = default(Nullable<int>);
					}
					this.SendPropertyChanged("eMarca");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_eCanjes(eCanje entity)
		{
			this.SendPropertyChanging();
			entity.eProducto = this;
		}
		
		private void detach_eCanjes(eCanje entity)
		{
			this.SendPropertyChanging();
			entity.eProducto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Marca")]
	public partial class eMarca : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre;
		
		private string _descripcion;
		
		private EntitySet<eProducto> _eProductos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public eMarca()
		{
			this._eProductos = new EntitySet<eProducto>(new Action<eProducto>(this.attach_eProductos), new Action<eProducto>(this.detach_eProductos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(255)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Marca_Producto", Storage="_eProductos", ThisKey="id", OtherKey="fkMarca")]
		public EntitySet<eProducto> eProductos
		{
			get
			{
				return this._eProductos;
			}
			set
			{
				this._eProductos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_eProductos(eProducto entity)
		{
			this.SendPropertyChanging();
			entity.eMarca = this;
		}
		
		private void detach_eProductos(eProducto entity)
		{
			this.SendPropertyChanging();
			entity.eMarca = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LugarRetiro")]
	public partial class eLugarRetiro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre;
		
		private string _descripcion;
		
		private EntitySet<eCanje> _eCanjes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public eLugarRetiro()
		{
			this._eCanjes = new EntitySet<eCanje>(new Action<eCanje>(this.attach_eCanjes), new Action<eCanje>(this.detach_eCanjes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(255)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LugarRetiro_Canje", Storage="_eCanjes", ThisKey="id", OtherKey="fkLugar")]
		public EntitySet<eCanje> eCanjes
		{
			get
			{
				return this._eCanjes;
			}
			set
			{
				this._eCanjes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_eCanjes(eCanje entity)
		{
			this.SendPropertyChanging();
			entity.eLugarRetiro = this;
		}
		
		private void detach_eCanjes(eCanje entity)
		{
			this.SendPropertyChanging();
			entity.eLugarRetiro = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Localidad")]
	public partial class eLocalidad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre;
		
		private System.Nullable<int> _fkCiudad;
		
		private EntitySet<eSocio> _eSocios;
		
		private EntitySet<eEmpleado> _eEmpleados;
		
		private EntityRef<eCiudad> _eCiudad;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnfkCiudadChanging(System.Nullable<int> value);
    partial void OnfkCiudadChanged();
    #endregion
		
		public eLocalidad()
		{
			this._eSocios = new EntitySet<eSocio>(new Action<eSocio>(this.attach_eSocios), new Action<eSocio>(this.detach_eSocios));
			this._eEmpleados = new EntitySet<eEmpleado>(new Action<eEmpleado>(this.attach_eEmpleados), new Action<eEmpleado>(this.detach_eEmpleados));
			this._eCiudad = default(EntityRef<eCiudad>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkCiudad", DbType="Int")]
		public System.Nullable<int> fkCiudad
		{
			get
			{
				return this._fkCiudad;
			}
			set
			{
				if ((this._fkCiudad != value))
				{
					if (this._eCiudad.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkCiudadChanging(value);
					this.SendPropertyChanging();
					this._fkCiudad = value;
					this.SendPropertyChanged("fkCiudad");
					this.OnfkCiudadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Localidad_Socio", Storage="_eSocios", ThisKey="id", OtherKey="fkLocalidad")]
		public EntitySet<eSocio> eSocios
		{
			get
			{
				return this._eSocios;
			}
			set
			{
				this._eSocios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Localidad_Empleado", Storage="_eEmpleados", ThisKey="id", OtherKey="fkLocalidad")]
		public EntitySet<eEmpleado> eEmpleados
		{
			get
			{
				return this._eEmpleados;
			}
			set
			{
				this._eEmpleados.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ciudad_Localidad", Storage="_eCiudad", ThisKey="fkCiudad", OtherKey="id", IsForeignKey=true)]
		public eCiudad eCiudad
		{
			get
			{
				return this._eCiudad.Entity;
			}
			set
			{
				eCiudad previousValue = this._eCiudad.Entity;
				if (((previousValue != value) 
							|| (this._eCiudad.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eCiudad.Entity = null;
						previousValue.eLocalidads.Remove(this);
					}
					this._eCiudad.Entity = value;
					if ((value != null))
					{
						value.eLocalidads.Add(this);
						this._fkCiudad = value.id;
					}
					else
					{
						this._fkCiudad = default(Nullable<int>);
					}
					this.SendPropertyChanged("eCiudad");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_eSocios(eSocio entity)
		{
			this.SendPropertyChanging();
			entity.eLocalidad = this;
		}
		
		private void detach_eSocios(eSocio entity)
		{
			this.SendPropertyChanging();
			entity.eLocalidad = null;
		}
		
		private void attach_eEmpleados(eEmpleado entity)
		{
			this.SendPropertyChanging();
			entity.eLocalidad = this;
		}
		
		private void detach_eEmpleados(eEmpleado entity)
		{
			this.SendPropertyChanging();
			entity.eLocalidad = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empleado")]
	public partial class eEmpleado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _dni;
		
		private string _apyn;
		
		private System.Nullable<System.DateTime> _fecnac;
		
		private System.Nullable<int> _fkLocalidad;
		
		private EntitySet<eCargaCombustibleSocio> _eCargaCombustibleSocios;
		
		private EntitySet<eCargaCombustible> _eCargaCombustibles;
		
		private EntityRef<eLocalidad> _eLocalidad;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndniChanging(int value);
    partial void OndniChanged();
    partial void OnapynChanging(string value);
    partial void OnapynChanged();
    partial void OnfecnacChanging(System.Nullable<System.DateTime> value);
    partial void OnfecnacChanged();
    partial void OnfkLocalidadChanging(System.Nullable<int> value);
    partial void OnfkLocalidadChanged();
    #endregion
		
		public eEmpleado()
		{
			this._eCargaCombustibleSocios = new EntitySet<eCargaCombustibleSocio>(new Action<eCargaCombustibleSocio>(this.attach_eCargaCombustibleSocios), new Action<eCargaCombustibleSocio>(this.detach_eCargaCombustibleSocios));
			this._eCargaCombustibles = new EntitySet<eCargaCombustible>(new Action<eCargaCombustible>(this.attach_eCargaCombustibles), new Action<eCargaCombustible>(this.detach_eCargaCombustibles));
			this._eLocalidad = default(EntityRef<eLocalidad>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dni", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int dni
		{
			get
			{
				return this._dni;
			}
			set
			{
				if ((this._dni != value))
				{
					this.OndniChanging(value);
					this.SendPropertyChanging();
					this._dni = value;
					this.SendPropertyChanged("dni");
					this.OndniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apyn", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string apyn
		{
			get
			{
				return this._apyn;
			}
			set
			{
				if ((this._apyn != value))
				{
					this.OnapynChanging(value);
					this.SendPropertyChanging();
					this._apyn = value;
					this.SendPropertyChanged("apyn");
					this.OnapynChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecnac", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecnac
		{
			get
			{
				return this._fecnac;
			}
			set
			{
				if ((this._fecnac != value))
				{
					this.OnfecnacChanging(value);
					this.SendPropertyChanging();
					this._fecnac = value;
					this.SendPropertyChanged("fecnac");
					this.OnfecnacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkLocalidad", DbType="Int")]
		public System.Nullable<int> fkLocalidad
		{
			get
			{
				return this._fkLocalidad;
			}
			set
			{
				if ((this._fkLocalidad != value))
				{
					if (this._eLocalidad.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkLocalidadChanging(value);
					this.SendPropertyChanging();
					this._fkLocalidad = value;
					this.SendPropertyChanged("fkLocalidad");
					this.OnfkLocalidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_CargaCombustibleSocio", Storage="_eCargaCombustibleSocios", ThisKey="dni", OtherKey="fkEmpleado")]
		public EntitySet<eCargaCombustibleSocio> eCargaCombustibleSocios
		{
			get
			{
				return this._eCargaCombustibleSocios;
			}
			set
			{
				this._eCargaCombustibleSocios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_CargaCombustible", Storage="_eCargaCombustibles", ThisKey="dni", OtherKey="fkEmpleado")]
		public EntitySet<eCargaCombustible> eCargaCombustibles
		{
			get
			{
				return this._eCargaCombustibles;
			}
			set
			{
				this._eCargaCombustibles.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Localidad_Empleado", Storage="_eLocalidad", ThisKey="fkLocalidad", OtherKey="id", IsForeignKey=true)]
		public eLocalidad eLocalidad
		{
			get
			{
				return this._eLocalidad.Entity;
			}
			set
			{
				eLocalidad previousValue = this._eLocalidad.Entity;
				if (((previousValue != value) 
							|| (this._eLocalidad.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eLocalidad.Entity = null;
						previousValue.eEmpleados.Remove(this);
					}
					this._eLocalidad.Entity = value;
					if ((value != null))
					{
						value.eEmpleados.Add(this);
						this._fkLocalidad = value.id;
					}
					else
					{
						this._fkLocalidad = default(Nullable<int>);
					}
					this.SendPropertyChanged("eLocalidad");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_eCargaCombustibleSocios(eCargaCombustibleSocio entity)
		{
			this.SendPropertyChanging();
			entity.eEmpleado = this;
		}
		
		private void detach_eCargaCombustibleSocios(eCargaCombustibleSocio entity)
		{
			this.SendPropertyChanging();
			entity.eEmpleado = null;
		}
		
		private void attach_eCargaCombustibles(eCargaCombustible entity)
		{
			this.SendPropertyChanging();
			entity.eEmpleado = this;
		}
		
		private void detach_eCargaCombustibles(eCargaCombustible entity)
		{
			this.SendPropertyChanging();
			entity.eEmpleado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Combustible")]
	public partial class eCombustible : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre;
		
		private System.Nullable<double> _precioPorLitro;
		
		private string _fkTipo;
		
		private EntitySet<eCargaCombustibleSocio> _eCargaCombustibleSocios;
		
		private EntitySet<eCargaCombustible> _eCargaCombustibles;
		
		private EntityRef<eTipoCombustible> _eTipoCombustible;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnprecioPorLitroChanging(System.Nullable<double> value);
    partial void OnprecioPorLitroChanged();
    partial void OnfkTipoChanging(string value);
    partial void OnfkTipoChanged();
    #endregion
		
		public eCombustible()
		{
			this._eCargaCombustibleSocios = new EntitySet<eCargaCombustibleSocio>(new Action<eCargaCombustibleSocio>(this.attach_eCargaCombustibleSocios), new Action<eCargaCombustibleSocio>(this.detach_eCargaCombustibleSocios));
			this._eCargaCombustibles = new EntitySet<eCargaCombustible>(new Action<eCargaCombustible>(this.attach_eCargaCombustibles), new Action<eCargaCombustible>(this.detach_eCargaCombustibles));
			this._eTipoCombustible = default(EntityRef<eTipoCombustible>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precioPorLitro", DbType="Float")]
		public System.Nullable<double> precioPorLitro
		{
			get
			{
				return this._precioPorLitro;
			}
			set
			{
				if ((this._precioPorLitro != value))
				{
					this.OnprecioPorLitroChanging(value);
					this.SendPropertyChanging();
					this._precioPorLitro = value;
					this.SendPropertyChanged("precioPorLitro");
					this.OnprecioPorLitroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkTipo", DbType="VarChar(30)")]
		public string fkTipo
		{
			get
			{
				return this._fkTipo;
			}
			set
			{
				if ((this._fkTipo != value))
				{
					if (this._eTipoCombustible.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkTipoChanging(value);
					this.SendPropertyChanging();
					this._fkTipo = value;
					this.SendPropertyChanged("fkTipo");
					this.OnfkTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Combustible_CargaCombustibleSocio", Storage="_eCargaCombustibleSocios", ThisKey="id", OtherKey="fkCombustible")]
		public EntitySet<eCargaCombustibleSocio> eCargaCombustibleSocios
		{
			get
			{
				return this._eCargaCombustibleSocios;
			}
			set
			{
				this._eCargaCombustibleSocios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Combustible_CargaCombustible", Storage="_eCargaCombustibles", ThisKey="id", OtherKey="fkCombustible")]
		public EntitySet<eCargaCombustible> eCargaCombustibles
		{
			get
			{
				return this._eCargaCombustibles;
			}
			set
			{
				this._eCargaCombustibles.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoCombustible_Combustible", Storage="_eTipoCombustible", ThisKey="fkTipo", OtherKey="nombre", IsForeignKey=true)]
		public eTipoCombustible eTipoCombustible
		{
			get
			{
				return this._eTipoCombustible.Entity;
			}
			set
			{
				eTipoCombustible previousValue = this._eTipoCombustible.Entity;
				if (((previousValue != value) 
							|| (this._eTipoCombustible.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eTipoCombustible.Entity = null;
						previousValue.eCombustibles.Remove(this);
					}
					this._eTipoCombustible.Entity = value;
					if ((value != null))
					{
						value.eCombustibles.Add(this);
						this._fkTipo = value.nombre;
					}
					else
					{
						this._fkTipo = default(string);
					}
					this.SendPropertyChanged("eTipoCombustible");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_eCargaCombustibleSocios(eCargaCombustibleSocio entity)
		{
			this.SendPropertyChanging();
			entity.eCombustible = this;
		}
		
		private void detach_eCargaCombustibleSocios(eCargaCombustibleSocio entity)
		{
			this.SendPropertyChanging();
			entity.eCombustible = null;
		}
		
		private void attach_eCargaCombustibles(eCargaCombustible entity)
		{
			this.SendPropertyChanging();
			entity.eCombustible = this;
		}
		
		private void detach_eCargaCombustibles(eCargaCombustible entity)
		{
			this.SendPropertyChanging();
			entity.eCombustible = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ciudad")]
	public partial class eCiudad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre;
		
		private string _descripcion;
		
		private EntitySet<eLocalidad> _eLocalidads;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public eCiudad()
		{
			this._eLocalidads = new EntitySet<eLocalidad>(new Action<eLocalidad>(this.attach_eLocalidads), new Action<eLocalidad>(this.detach_eLocalidads));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(255)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ciudad_Localidad", Storage="_eLocalidads", ThisKey="id", OtherKey="fkCiudad")]
		public EntitySet<eLocalidad> eLocalidads
		{
			get
			{
				return this._eLocalidads;
			}
			set
			{
				this._eLocalidads.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_eLocalidads(eLocalidad entity)
		{
			this.SendPropertyChanging();
			entity.eCiudad = this;
		}
		
		private void detach_eLocalidads(eLocalidad entity)
		{
			this.SendPropertyChanging();
			entity.eCiudad = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CargaCombustibleSocio")]
	public partial class eCargaCombustibleSocio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<double> _precio;
		
		private System.Nullable<double> _cantidad;
		
		private System.Nullable<int> _puntos;
		
		private System.Nullable<System.DateTime> _fechaHora;
		
		private System.Nullable<int> _fkCombustible;
		
		private System.Nullable<int> _fkPago;
		
		private System.Nullable<int> _fkEmpleado;
		
		private System.Nullable<int> _fkSocio;
		
		private EntityRef<eCombustible> _eCombustible;
		
		private EntityRef<eEmpleado> _eEmpleado;
		
		private EntityRef<eTipoPago> _eTipoPago;
		
		private EntityRef<eSocio> _eSocio;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnprecioChanging(System.Nullable<double> value);
    partial void OnprecioChanged();
    partial void OncantidadChanging(System.Nullable<double> value);
    partial void OncantidadChanged();
    partial void OnpuntosChanging(System.Nullable<int> value);
    partial void OnpuntosChanged();
    partial void OnfechaHoraChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaHoraChanged();
    partial void OnfkCombustibleChanging(System.Nullable<int> value);
    partial void OnfkCombustibleChanged();
    partial void OnfkPagoChanging(System.Nullable<int> value);
    partial void OnfkPagoChanged();
    partial void OnfkEmpleadoChanging(System.Nullable<int> value);
    partial void OnfkEmpleadoChanged();
    partial void OnfkSocioChanging(System.Nullable<int> value);
    partial void OnfkSocioChanged();
    #endregion
		
		public eCargaCombustibleSocio()
		{
			this._eCombustible = default(EntityRef<eCombustible>);
			this._eEmpleado = default(EntityRef<eEmpleado>);
			this._eTipoPago = default(EntityRef<eTipoPago>);
			this._eSocio = default(EntityRef<eSocio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Float")]
		public System.Nullable<double> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Float")]
		public System.Nullable<double> cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puntos", DbType="Int")]
		public System.Nullable<int> puntos
		{
			get
			{
				return this._puntos;
			}
			set
			{
				if ((this._puntos != value))
				{
					this.OnpuntosChanging(value);
					this.SendPropertyChanging();
					this._puntos = value;
					this.SendPropertyChanged("puntos");
					this.OnpuntosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaHora", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaHora
		{
			get
			{
				return this._fechaHora;
			}
			set
			{
				if ((this._fechaHora != value))
				{
					this.OnfechaHoraChanging(value);
					this.SendPropertyChanging();
					this._fechaHora = value;
					this.SendPropertyChanged("fechaHora");
					this.OnfechaHoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkCombustible", DbType="Int")]
		public System.Nullable<int> fkCombustible
		{
			get
			{
				return this._fkCombustible;
			}
			set
			{
				if ((this._fkCombustible != value))
				{
					if (this._eCombustible.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkCombustibleChanging(value);
					this.SendPropertyChanging();
					this._fkCombustible = value;
					this.SendPropertyChanged("fkCombustible");
					this.OnfkCombustibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkPago", DbType="Int")]
		public System.Nullable<int> fkPago
		{
			get
			{
				return this._fkPago;
			}
			set
			{
				if ((this._fkPago != value))
				{
					if (this._eTipoPago.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkPagoChanging(value);
					this.SendPropertyChanging();
					this._fkPago = value;
					this.SendPropertyChanged("fkPago");
					this.OnfkPagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkEmpleado", DbType="Int")]
		public System.Nullable<int> fkEmpleado
		{
			get
			{
				return this._fkEmpleado;
			}
			set
			{
				if ((this._fkEmpleado != value))
				{
					if (this._eEmpleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._fkEmpleado = value;
					this.SendPropertyChanged("fkEmpleado");
					this.OnfkEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkSocio", DbType="Int")]
		public System.Nullable<int> fkSocio
		{
			get
			{
				return this._fkSocio;
			}
			set
			{
				if ((this._fkSocio != value))
				{
					if (this._eSocio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkSocioChanging(value);
					this.SendPropertyChanging();
					this._fkSocio = value;
					this.SendPropertyChanged("fkSocio");
					this.OnfkSocioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Combustible_CargaCombustibleSocio", Storage="_eCombustible", ThisKey="fkCombustible", OtherKey="id", IsForeignKey=true)]
		public eCombustible eCombustible
		{
			get
			{
				return this._eCombustible.Entity;
			}
			set
			{
				eCombustible previousValue = this._eCombustible.Entity;
				if (((previousValue != value) 
							|| (this._eCombustible.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eCombustible.Entity = null;
						previousValue.eCargaCombustibleSocios.Remove(this);
					}
					this._eCombustible.Entity = value;
					if ((value != null))
					{
						value.eCargaCombustibleSocios.Add(this);
						this._fkCombustible = value.id;
					}
					else
					{
						this._fkCombustible = default(Nullable<int>);
					}
					this.SendPropertyChanged("eCombustible");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_CargaCombustibleSocio", Storage="_eEmpleado", ThisKey="fkEmpleado", OtherKey="dni", IsForeignKey=true)]
		public eEmpleado eEmpleado
		{
			get
			{
				return this._eEmpleado.Entity;
			}
			set
			{
				eEmpleado previousValue = this._eEmpleado.Entity;
				if (((previousValue != value) 
							|| (this._eEmpleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eEmpleado.Entity = null;
						previousValue.eCargaCombustibleSocios.Remove(this);
					}
					this._eEmpleado.Entity = value;
					if ((value != null))
					{
						value.eCargaCombustibleSocios.Add(this);
						this._fkEmpleado = value.dni;
					}
					else
					{
						this._fkEmpleado = default(Nullable<int>);
					}
					this.SendPropertyChanged("eEmpleado");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoPago_CargaCombustibleSocio", Storage="_eTipoPago", ThisKey="fkPago", OtherKey="id", IsForeignKey=true)]
		public eTipoPago eTipoPago
		{
			get
			{
				return this._eTipoPago.Entity;
			}
			set
			{
				eTipoPago previousValue = this._eTipoPago.Entity;
				if (((previousValue != value) 
							|| (this._eTipoPago.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eTipoPago.Entity = null;
						previousValue.eCargaCombustibleSocios.Remove(this);
					}
					this._eTipoPago.Entity = value;
					if ((value != null))
					{
						value.eCargaCombustibleSocios.Add(this);
						this._fkPago = value.id;
					}
					else
					{
						this._fkPago = default(Nullable<int>);
					}
					this.SendPropertyChanged("eTipoPago");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Socio_CargaCombustibleSocio", Storage="_eSocio", ThisKey="fkSocio", OtherKey="numSocio", IsForeignKey=true)]
		public eSocio eSocio
		{
			get
			{
				return this._eSocio.Entity;
			}
			set
			{
				eSocio previousValue = this._eSocio.Entity;
				if (((previousValue != value) 
							|| (this._eSocio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eSocio.Entity = null;
						previousValue.eCargaCombustibleSocios.Remove(this);
					}
					this._eSocio.Entity = value;
					if ((value != null))
					{
						value.eCargaCombustibleSocios.Add(this);
						this._fkSocio = value.numSocio;
					}
					else
					{
						this._fkSocio = default(Nullable<int>);
					}
					this.SendPropertyChanged("eSocio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CargaCombustible")]
	public partial class eCargaCombustible : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<double> _precio;
		
		private System.Nullable<double> _cantidad;
		
		private System.Nullable<System.DateTime> _fechaHora;
		
		private System.Nullable<int> _fkCombustible;
		
		private System.Nullable<int> _fkPago;
		
		private System.Nullable<int> _fkEmpleado;
		
		private EntityRef<eCombustible> _eCombustible;
		
		private EntityRef<eEmpleado> _eEmpleado;
		
		private EntityRef<eTipoPago> _eTipoPago;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnprecioChanging(System.Nullable<double> value);
    partial void OnprecioChanged();
    partial void OncantidadChanging(System.Nullable<double> value);
    partial void OncantidadChanged();
    partial void OnfechaHoraChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaHoraChanged();
    partial void OnfkCombustibleChanging(System.Nullable<int> value);
    partial void OnfkCombustibleChanged();
    partial void OnfkPagoChanging(System.Nullable<int> value);
    partial void OnfkPagoChanged();
    partial void OnfkEmpleadoChanging(System.Nullable<int> value);
    partial void OnfkEmpleadoChanged();
    #endregion
		
		public eCargaCombustible()
		{
			this._eCombustible = default(EntityRef<eCombustible>);
			this._eEmpleado = default(EntityRef<eEmpleado>);
			this._eTipoPago = default(EntityRef<eTipoPago>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Float")]
		public System.Nullable<double> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Float")]
		public System.Nullable<double> cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaHora", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaHora
		{
			get
			{
				return this._fechaHora;
			}
			set
			{
				if ((this._fechaHora != value))
				{
					this.OnfechaHoraChanging(value);
					this.SendPropertyChanging();
					this._fechaHora = value;
					this.SendPropertyChanged("fechaHora");
					this.OnfechaHoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkCombustible", DbType="Int")]
		public System.Nullable<int> fkCombustible
		{
			get
			{
				return this._fkCombustible;
			}
			set
			{
				if ((this._fkCombustible != value))
				{
					if (this._eCombustible.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkCombustibleChanging(value);
					this.SendPropertyChanging();
					this._fkCombustible = value;
					this.SendPropertyChanged("fkCombustible");
					this.OnfkCombustibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkPago", DbType="Int")]
		public System.Nullable<int> fkPago
		{
			get
			{
				return this._fkPago;
			}
			set
			{
				if ((this._fkPago != value))
				{
					if (this._eTipoPago.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkPagoChanging(value);
					this.SendPropertyChanging();
					this._fkPago = value;
					this.SendPropertyChanged("fkPago");
					this.OnfkPagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkEmpleado", DbType="Int")]
		public System.Nullable<int> fkEmpleado
		{
			get
			{
				return this._fkEmpleado;
			}
			set
			{
				if ((this._fkEmpleado != value))
				{
					if (this._eEmpleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._fkEmpleado = value;
					this.SendPropertyChanged("fkEmpleado");
					this.OnfkEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Combustible_CargaCombustible", Storage="_eCombustible", ThisKey="fkCombustible", OtherKey="id", IsForeignKey=true)]
		public eCombustible eCombustible
		{
			get
			{
				return this._eCombustible.Entity;
			}
			set
			{
				eCombustible previousValue = this._eCombustible.Entity;
				if (((previousValue != value) 
							|| (this._eCombustible.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eCombustible.Entity = null;
						previousValue.eCargaCombustibles.Remove(this);
					}
					this._eCombustible.Entity = value;
					if ((value != null))
					{
						value.eCargaCombustibles.Add(this);
						this._fkCombustible = value.id;
					}
					else
					{
						this._fkCombustible = default(Nullable<int>);
					}
					this.SendPropertyChanged("eCombustible");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_CargaCombustible", Storage="_eEmpleado", ThisKey="fkEmpleado", OtherKey="dni", IsForeignKey=true)]
		public eEmpleado eEmpleado
		{
			get
			{
				return this._eEmpleado.Entity;
			}
			set
			{
				eEmpleado previousValue = this._eEmpleado.Entity;
				if (((previousValue != value) 
							|| (this._eEmpleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eEmpleado.Entity = null;
						previousValue.eCargaCombustibles.Remove(this);
					}
					this._eEmpleado.Entity = value;
					if ((value != null))
					{
						value.eCargaCombustibles.Add(this);
						this._fkEmpleado = value.dni;
					}
					else
					{
						this._fkEmpleado = default(Nullable<int>);
					}
					this.SendPropertyChanged("eEmpleado");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoPago_CargaCombustible", Storage="_eTipoPago", ThisKey="fkPago", OtherKey="id", IsForeignKey=true)]
		public eTipoPago eTipoPago
		{
			get
			{
				return this._eTipoPago.Entity;
			}
			set
			{
				eTipoPago previousValue = this._eTipoPago.Entity;
				if (((previousValue != value) 
							|| (this._eTipoPago.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eTipoPago.Entity = null;
						previousValue.eCargaCombustibles.Remove(this);
					}
					this._eTipoPago.Entity = value;
					if ((value != null))
					{
						value.eCargaCombustibles.Add(this);
						this._fkPago = value.id;
					}
					else
					{
						this._fkPago = default(Nullable<int>);
					}
					this.SendPropertyChanged("eTipoPago");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Canje")]
	public partial class eCanje : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _numCanje;
		
		private System.Nullable<int> _valor;
		
		private System.Nullable<int> _fkSocio;
		
		private System.Nullable<int> _fkProducto;
		
		private System.Nullable<int> _fkLugar;
		
		private EntityRef<eLugarRetiro> _eLugarRetiro;
		
		private EntityRef<eProducto> _eProducto;
		
		private EntityRef<eSocio> _eSocio;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnumCanjeChanging(int value);
    partial void OnnumCanjeChanged();
    partial void OnvalorChanging(System.Nullable<int> value);
    partial void OnvalorChanged();
    partial void OnfkSocioChanging(System.Nullable<int> value);
    partial void OnfkSocioChanged();
    partial void OnfkProductoChanging(System.Nullable<int> value);
    partial void OnfkProductoChanged();
    partial void OnfkLugarChanging(System.Nullable<int> value);
    partial void OnfkLugarChanged();
    #endregion
		
		public eCanje()
		{
			this._eLugarRetiro = default(EntityRef<eLugarRetiro>);
			this._eProducto = default(EntityRef<eProducto>);
			this._eSocio = default(EntityRef<eSocio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numCanje", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int numCanje
		{
			get
			{
				return this._numCanje;
			}
			set
			{
				if ((this._numCanje != value))
				{
					this.OnnumCanjeChanging(value);
					this.SendPropertyChanging();
					this._numCanje = value;
					this.SendPropertyChanged("numCanje");
					this.OnnumCanjeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="Int")]
		public System.Nullable<int> valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnvalorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("valor");
					this.OnvalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkSocio", DbType="Int")]
		public System.Nullable<int> fkSocio
		{
			get
			{
				return this._fkSocio;
			}
			set
			{
				if ((this._fkSocio != value))
				{
					if (this._eSocio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkSocioChanging(value);
					this.SendPropertyChanging();
					this._fkSocio = value;
					this.SendPropertyChanged("fkSocio");
					this.OnfkSocioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkProducto", DbType="Int")]
		public System.Nullable<int> fkProducto
		{
			get
			{
				return this._fkProducto;
			}
			set
			{
				if ((this._fkProducto != value))
				{
					if (this._eProducto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkProductoChanging(value);
					this.SendPropertyChanging();
					this._fkProducto = value;
					this.SendPropertyChanged("fkProducto");
					this.OnfkProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkLugar", DbType="Int")]
		public System.Nullable<int> fkLugar
		{
			get
			{
				return this._fkLugar;
			}
			set
			{
				if ((this._fkLugar != value))
				{
					if (this._eLugarRetiro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkLugarChanging(value);
					this.SendPropertyChanging();
					this._fkLugar = value;
					this.SendPropertyChanged("fkLugar");
					this.OnfkLugarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LugarRetiro_Canje", Storage="_eLugarRetiro", ThisKey="fkLugar", OtherKey="id", IsForeignKey=true)]
		public eLugarRetiro eLugarRetiro
		{
			get
			{
				return this._eLugarRetiro.Entity;
			}
			set
			{
				eLugarRetiro previousValue = this._eLugarRetiro.Entity;
				if (((previousValue != value) 
							|| (this._eLugarRetiro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eLugarRetiro.Entity = null;
						previousValue.eCanjes.Remove(this);
					}
					this._eLugarRetiro.Entity = value;
					if ((value != null))
					{
						value.eCanjes.Add(this);
						this._fkLugar = value.id;
					}
					else
					{
						this._fkLugar = default(Nullable<int>);
					}
					this.SendPropertyChanged("eLugarRetiro");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Canje", Storage="_eProducto", ThisKey="fkProducto", OtherKey="id", IsForeignKey=true)]
		public eProducto eProducto
		{
			get
			{
				return this._eProducto.Entity;
			}
			set
			{
				eProducto previousValue = this._eProducto.Entity;
				if (((previousValue != value) 
							|| (this._eProducto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eProducto.Entity = null;
						previousValue.eCanjes.Remove(this);
					}
					this._eProducto.Entity = value;
					if ((value != null))
					{
						value.eCanjes.Add(this);
						this._fkProducto = value.id;
					}
					else
					{
						this._fkProducto = default(Nullable<int>);
					}
					this.SendPropertyChanged("eProducto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Socio_Canje", Storage="_eSocio", ThisKey="fkSocio", OtherKey="numSocio", IsForeignKey=true)]
		public eSocio eSocio
		{
			get
			{
				return this._eSocio.Entity;
			}
			set
			{
				eSocio previousValue = this._eSocio.Entity;
				if (((previousValue != value) 
							|| (this._eSocio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eSocio.Entity = null;
						previousValue.eCanjes.Remove(this);
					}
					this._eSocio.Entity = value;
					if ((value != null))
					{
						value.eCanjes.Add(this);
						this._fkSocio = value.numSocio;
					}
					else
					{
						this._fkSocio = default(Nullable<int>);
					}
					this.SendPropertyChanged("eSocio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
